name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: npm install
        uses: actions/checkout@v2
        with:
          args: install
      - name: npm test
        uses: actions/checkout@v2
        with:
          args: run test
      - name: npm lint
        uses: actions/checkout@v2
        with:
          args: run lint

  build:
    runs-on: ubuntu-latest
    needs: [build_test]
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: itsmaniche18/todo-node:latest
